.TH "tune" "1" "March 2009" "" "User Manuals"
.SH NAME
.LP
.B
tune \- sine wave generator for playing musical notes and other frequencies.
.SH SYNOPSIS
.LP
\fBtune\fR \fICOMMAND\fR \fI[OPTION]\fR... \fI[NOTE]\fR...
.SH DESCRIPTION
.LP
Blah

.SH OPTIONS
.TP
\fB-h\fR, \fB--help\fR
Print the help and usage and exit.

.SH "SEE ALSO"
.LP
\fBaplay(1)\fR,
\fBffmpeg(1)\fR

.SH AUTHORS
.LP
James Webber

.SH COPYRIGHT
.LP
Copyright (C) James Webber 2009.  Distributed under a 3-clause BSD licence.
See COPYING.

